#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login_check:
  path: /login_check
admin_login_check:
  path: /admin/login_check
sign_up:
  path: /signup
login:
  path: /login
home:
  path : /
cars:
  path: /cars
  controller: App\Controller\CarsController::cars.list
cars_add:
  path: /admin/panel/cars/add
  controller: App\Controller\CarsController::addCar
cars_update:
  path: /admin/panel/cars/update
  controller: App\Controller\CarsController::updateCar

admin_panel:
  path : /admin/panel
  controller: App\Controller\AdminPanelController::loadPanel
cars_order:
  path : /order
  controller: App\Controller\OrdersController::orderCar

tariff_add:
  path: /admin/panel/tariff/add
  controller: App\Controller\TariffController::addTariff
user_orders:
  path: /user/personal/orders
  controller: App\Controller\OrdersController::userOrders
#carByID:
#  path : /cars/{id}
#  controller : App\Controller\CarsController::cars.carByID